### ISSUE TITLE
Does the baseline support multi-gpu training?

### ISSUE THREAD

**Issue by treya-lin** [FinvDialect/2023_finvcup_baseline#2]
I have 10G of memory per GPU. Training with one single gpu causes CUDA OOM error. Does the baseline support traning on more than one GPUs?

Or is it because the code did not release memory in time during training?

Log:
```
2023_finvcup_baseline$ python train.py --loss PairDistanceLoss --max_epoch 80 --device cuda:0 --save_path ./exps_pairdist/ 2>&1 |tee pairdist_20230712.log
train_data_shape: (84623, 3)
valid_data_shape: (21156, 3)
07-12 14:48:33 Model para number = 14.73
07-12 15:01:18 [ 1] Lr: 0.001000, Training: 100.00%,  Loss: 1276.00593
0it [00:01, ?it/s]
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    eval_losses.append(s.eval_network(loader=evalLoader))
  File "/home/linyikan/workspace/asr_space/project_space/2023_finvcup_baseline/utils/ECAPAModel.py", line 63, in eval_network
    embedding = self.dialect_encoder.forward(data, aug = False)
  File "/home/linyikan/workspace/asr_space/project_space/2023_finvcup_baseline/utils/model.py", line 210, in forward
    sg = torch.sqrt( ( torch.sum((x**2) * w, dim=2) - mu**2 ).clamp(min=1e-4) )
RuntimeError: CUDA out of memory. Tried to allocate 1.10 GiB (GPU 0; 10.92 GiB total capacity; 9.16 GiB already allocated; 872.06 MiB free; 9.27 GiB reserved in total by PyTorch)
```

**Comment by yjegssl** [comment]
Hi @treya-lin 

Thank you for opening the issue.The baseline does not support multi-GPU training up to now. You can realize it refrefering[https://pytorch.org/docs/1.9.0/distributed.html?highlight=distribute#module-torch.distributed](url). To avoid OOM problem, you can adjust batch size to a smaller number.

**Comment by treya-lin** [comment]
> Hi @treya-lin
> 
> Thank you for opening the issue.The baseline does not support multi-GPU training up to now. You can realize it refrefering[https://pytorch.org/docs/1.9.0/distributed.html?highlight=distribute#module-torch.distributed](url). To avoid OOM problem, you can adjust batch size to a smaller number.

Hi thanks for the reply. I see! Didn't realize the default batch_size was 128.

ps: for those who might be interested, with the default setting, it requires about 18G GPU memory as tested.
