### ISSUE TITLE
baseline跑完之后39.144774

### ISSUE THREAD

**Issue by yanqiangmiffy** [FinvDialect/2023_finvcup_baseline#3]
运行命令为：

python train.py --loss aamsoftmax --max_epoch 80 --device cuda:0 --save_path ./exps/

python inference.py --model_path exps/model/model_0080.model --test_path data/test/pair_list.csv --device cuda:0

请问那里可能出错了？

**Comment by yjegssl** [comment]
谢谢你的issue。这个结果和我们内部测的差不多，执行命令没什么问题。aamsoftmax这个loss是把赛题当作分类问题解决，得出的距离会偏小很多。建议做一些尺度上的变换，或者直接使用第三种loss，效果会接近我们的baseline结果。

**Comment by yanqiangmiffy** [comment]
> 

收到，多谢回复
